export const cardTexts = [
  "Burn fat, build lean muscle, and boost your metabolism with our expert-led weight loss training programs. Our sessions combine high-intensity interval training, cardio, and strength exercises tailored to your fitness level. Receive personalized nutrition guidance and ongoing support from our certified trainers to help you stay motivated and achieve lasting results. Start your transformation today and reach your weight loss goals in a supportive and energetic environment!",

  "Discover the power and discipline of martial arts with our comprehensive training classes. Learn self-defense, improve your flexibility, and build confidence through structured lessons in various martial arts styles. Our experienced instructors focus on technique, fitness, and mental strength, ensuring a safe and motivating environment for all skill levels. Join us to enhance your agility, coordination, and overall well-being!",

  "Achieve balance and inner peace with our meditation and yoga sessions. Designed to reduce stress and improve flexibility, our classes blend mindful breathing, gentle stretching, and relaxation techniques. Whether you are a beginner or experienced, our instructors guide you through practices that nurture both body and mind, helping you find calm, clarity, and renewed energy in your daily life.",
  "Weightlifting: Building Strength and Power. Weightlifting focuses on increasing muscle mass, strength, and endurance through resistance training. It includes exercises like squats, deadlifts, bench presses, and Olympic lifts (snatch, clean & jerk). Key Benefits:Builds muscle and bone density, Boosts metabolism and fat loss, Improves athletic performance,Enhances functional strength for daily activities.",
  "Martial Arts: Discipline, Skill, and Self-Defense. Martial arts encompass various combat practices, such as Karate, Taekwondo, Brazilian Jiu-Jitsu, Muay Thai, and Kung Fu. Training includes striking, grappling, forms (katas), and sparring. Key Benefits: Develops self-defense skills, Enhances agility, reflexes, and coordination, Promotes mental discipline and focus, Builds confidence and resilience.",
  "Yoga: Flexibility, Mindfulness, and Balance. Yoga is an ancient practice combining physical postures (asanas), breath control (pranayama), and meditation. Styles range from Hatha (gentle) to Vinyasa (flow) and Power Yoga (intense). Key Benefits: Increases flexibility and mobility, Reduces stress and anxiety, Improves posture and core strength, Enhances mind-body connection.",
];
